[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "build"

[functions]
  directory = "../netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200