redirectsOrigin = "config"
plugins = []
functionsDirectory = "/Users/olga/netlify/functions"
functionsDirectoryOrigin = "config"
headers = []

[functions]

[functions."*"]
node_bundler = "esbuild"

[build]
publish = "/Users/olga/frontend/build"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/olga"
command = "cd frontend && npm install && npm run build"
functions = "/Users/olga/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]